### ISSUE TITLE
.destroy().restore() and .options() methods don't work on inline calendar

### ISSUE THREAD

**Issue by jordangarside** [bevacqua/rome#126]
When I do an inline calendar, with either default or custom options, the options method and the destroy then restore methods result in an empty rd-container.

**Comment by andrey-hohlov** [comment]
It works in v2.1.3, but broken from 2.1.4

I think reason there: https://github.com/bevacqua/rome/commit/78686fd3de8d50a8f3d1ce1600338a02249c9847

**Comment by oskarkrawczyk** [comment]
Just bumped into this issue. Interesting that it hasn't been addressed in all these releases.

**Comment by paddy01** [comment]
Still an issue in 2.1.22 .. tried reverting some of the changes in specific to the inline calendar #https://github.com/bevacqua/rome/commit/78686fd3de8d50a8f3d1ce1600338a02249c9847 but made no difference to the issue :(

**Comment by jmirmina** [comment]
We ran into this issue as well. We were able to get around it by specifying the `appendTo` option and chaining `show()`:

```
var element = document.getElementById('myContainer'),
    picker = rome(element);

picker.options({ appendTo: element }).show();
```
